### ISSUE TITLE
Remove Json.NET dependency

### ISSUE THREAD

**Issue by randomPoison** [kongregate/kongregate-web#1]
In order to communicate with the JavaScript API, there are a couple of places we need to convert data to and from JSON. Currently, we are using [Json.NET](https://www.newtonsoft.com/json) to do the serialization, however doing so forces users to import Json.NET into their project in order to use kongregate-web. Removing this dependency would simplify the process of importing kongregate-web into a project.

The serialization that we need to do are all fairly simple, so we should be able to use Unity's built-in [JSON serialization utility](https://docs.unity3d.com/Manual/JSONSerialization.html) with minor modifications to how we communicate with the JavaScript API.

**Comment by RichardVasquez** [comment]
I'm going to take a swing at this one, if that's ok.
