### ISSUE TITLE
Missing meta files

### ISSUE THREAD

**Issue by psociety** [kongregate/kongregate-web#12]
**Unity version**: 2019.3.7f1
**Package version**: latest
![image](https://user-images.githubusercontent.com/29523682/80302252-32386180-87a9-11ea-9f23-41a073c6802b.png)

Most of .cs files don't include a `.meta` file so unity ignores them :S It seems that unity only generates meta files for the ones in `/Assets/` folder.

I tried changed `/Runtime/` folder perms, but they're changed automatically again when opening the project. Copying the .cs files inside `/Assets/` folder so .metas are generated and copying them back to `/Runtime/` works.

**Comment by randomPoison** [comment]
Ah, sorry about that! I made the mistake of merging #9 without testing the changes, and caught too late that the change actually broke a number of things 🤦 If you're currently trying to use kongregate-web in a project, I recommend using the v0.1.0 tag, which points to the commit before #9 was merged and so is substantially less broken than what's currently on master. You can do this either by directly adding the Git dependency, or by using [the hosted version of the package on OpenUPM](https://openupm.com/packages/com.kongregate.kongregate-web/).

**Comment by randomPoison** [comment]
This should be resolved now that I've merged #11. However, I would still recommend using the 0.1.0 version of the package, rather than what's on master. If there are any further issues please don't hesitate to open another issue! ❤️
